# CMake generated Testfile for 
# Source directory: /home/jcc/Aleph2.0/tests
# Build directory: /home/jcc/Aleph2.0/cmake/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(barycentric_subdivision "test_barycentric_subdivision")
set_tests_properties(barycentric_subdivision PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;125;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(beta_skeleton "test_beta_skeleton")
set_tests_properties(beta_skeleton PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;126;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(bootstrap "test_bootstrap")
set_tests_properties(bootstrap PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;131;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(boundary_matrix_reduction "test_boundary_matrix_reduction")
set_tests_properties(boundary_matrix_reduction PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;134;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(cech_expansion "test_cech_expansion")
set_tests_properties(cech_expansion PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;135;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(clique_enumeration "test_clique_enumeration")
set_tests_properties(clique_enumeration PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;136;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(clique_graph "test_clique_graph")
set_tests_properties(clique_graph PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;137;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(combinatorial_curvature "test_combinatorial_curvature")
set_tests_properties(combinatorial_curvature PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;138;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(connected_components "test_connected_components")
set_tests_properties(connected_components PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;139;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(data_descriptors "test_data_descriptors")
set_tests_properties(data_descriptors PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;140;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(distances "test_distances")
set_tests_properties(distances PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;141;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(dowker_complex "test_dowker_complex")
set_tests_properties(dowker_complex PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;142;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(filesystem "test_filesystem")
set_tests_properties(filesystem PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;143;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(fractal_dimension "test_fractal_dimension")
set_tests_properties(fractal_dimension PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;144;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(graph_generation "test_graph_generation")
set_tests_properties(graph_generation PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;145;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(heat_kernel "test_heat_kernel")
set_tests_properties(heat_kernel PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;146;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_adjacency_matrix "test_io_adjacency_matrix")
set_tests_properties(io_adjacency_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;147;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_bipartite_adjacency_matrix "test_io_bipartite_adjacency_matrix")
set_tests_properties(io_bipartite_adjacency_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;148;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_functions "test_io_functions")
set_tests_properties(io_functions PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;149;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_gml "test_io_gml")
set_tests_properties(io_gml PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;150;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_lexicographic_triangulation "test_io_lexicographic_triangulation")
set_tests_properties(io_lexicographic_triangulation PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;164;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_pajek "test_io_pajek")
set_tests_properties(io_pajek PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;165;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_sparse_adjacency_matrix "test_io_sparse_adjacency_matrix")
set_tests_properties(io_sparse_adjacency_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;166;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(io_vtk "test_io_vtk")
set_tests_properties(io_vtk PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;167;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(kernel_density_estimator "test_kernel_density_estimator")
set_tests_properties(kernel_density_estimator PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;168;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(mesh "test_mesh")
set_tests_properties(mesh PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;169;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(munkres "test_munkres")
set_tests_properties(munkres PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;170;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(nearest_neighbours "test_nearest_neighbours")
set_tests_properties(nearest_neighbours PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;171;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(partitions "test_partitions")
set_tests_properties(partitions PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;172;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(persistence_diagrams "test_persistence_diagrams")
set_tests_properties(persistence_diagrams PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;173;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(persistent_homology_complete "test_persistent_homology_complete")
set_tests_properties(persistent_homology_complete PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;174;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(persistent_intersection_homology "test_persistent_intersection_homology")
set_tests_properties(persistent_intersection_homology PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;175;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(piecewise_linear_function "test_piecewise_linear_function")
set_tests_properties(piecewise_linear_function PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;176;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(principal_component_analysis "test_principal_component_analysis")
set_tests_properties(principal_component_analysis PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;177;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(point_clouds "test_point_clouds")
set_tests_properties(point_clouds PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;178;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(rips_expansion "test_rips_expansion")
set_tests_properties(rips_expansion PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;179;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(rips_skeleton "test_rips_skeleton")
set_tests_properties(rips_skeleton PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;180;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(spine "test_spine")
set_tests_properties(spine PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;181;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(step_function "test_step_function")
set_tests_properties(step_function PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;182;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(tangent_space "test_tangent_space")
set_tests_properties(tangent_space PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;183;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(union_find "test_union_find")
set_tests_properties(union_find PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;184;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
add_test(witness_complex "test_witness_complex")
set_tests_properties(witness_complex PROPERTIES  _BACKTRACE_TRIPLES "/home/jcc/Aleph2.0/tests/CMakeLists.txt;185;ADD_TEST;/home/jcc/Aleph2.0/tests/CMakeLists.txt;0;")
